name: Gradle Build Pipeline

on:
  push:
    branches: [ "NukkitMot" ]
  pull_request:
    branches: [ "NukkitMot" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
